import { Injectable, Logger } from '@nestjs/common';
import ffmpegPath from 'ffmpeg-static';
import ffmpeg from 'fluent-ffmpeg';
import { existsSync } from 'node:fs';
import { rename, rm, stat } from 'node:fs/promises';
import { KeyedLock } from '../common/keyed-lock';

if (ffmpegPath) {
  ffmpeg.setFfmpegPath(ffmpegPath);
}

const THUMBNAIL_WIDTH = 320;
/**
 * Camera firmware can emit a handful of garbage/black frames while the
 * sensor is still warming up at the start of a recording, so grabbing frame
 * 0 risks a blank thumbnail. Skip ahead this many frames first; if the
 * source turns out to be too short to have one (e.g. a single-frame live
 * snippet), fall back to frame 0 instead of failing.
 */
const RECORDING_THUMBNAIL_FRAME_SKIP = 2;

/**
 * Generates a sidecar thumbnail next to already-published media, on the
 * ingest path (image capture, recording-part completion, live-recording
 * completion, audio upload). Runs after MediaStorageService has published the
 * source file, mirroring TranscodingService's read-only relationship to
 * storage: this service never touches manifests, only sits beside them.
 *
 * Generation is idempotent (skips if the thumbnail already exists) and
 * best-effort from the caller's point of view -- a failure here must never
 * fail the ingest request, since the source media is already safely stored.
 */
@Injectable()
export class ThumbnailService {
  private readonly logger = new Logger(ThumbnailService.name);
  private readonly lock = new KeyedLock();

  /** JPEG thumbnail generated by downscaling a single already-published image (captures/timelapses). */
  async ensureFromImage(sourcePath: string, thumbnailPath: string): Promise<void> {
    await this.ensure(thumbnailPath, (temporaryPath) =>
      this.renderImage(sourcePath, temporaryPath),
    );
  }

  /** JPEG thumbnail generated by grabbing frame 1 out of an MJPEG source (recording parts or a completed live file). */
  async ensureFromMjpeg(sourcePath: string, thumbnailPath: string): Promise<void> {
    await this.ensure(thumbnailPath, (temporaryPath) =>
      this.renderMjpegFrame(sourcePath, temporaryPath),
    );
  }

  /** PNG waveform picture rendered directly from a WAV via ffmpeg's showwavespic filter. */
  async ensureWaveform(sourcePath: string, thumbnailPath: string): Promise<void> {
    await this.ensure(thumbnailPath, (temporaryPath) =>
      this.renderWaveform(sourcePath, temporaryPath),
    );
  }

  private async ensure(
    thumbnailPath: string,
    render: (temporaryPath: string) => Promise<void>,
  ): Promise<void> {
    if (existsSync(thumbnailPath)) return;
    await this.lock.run(thumbnailPath, async () => {
      if (existsSync(thumbnailPath)) return;
      const temporaryPath = `${thumbnailPath}.${Date.now()}.tmp`;
      try {
        await render(temporaryPath);
        await rename(temporaryPath, thumbnailPath);
      } catch (error) {
        this.logger.warn(
          `thumbnail generation failed for ${thumbnailPath}: ${(error as Error).message}`,
        );
      } finally {
        await rm(temporaryPath, { force: true });
      }
    });
  }

  private renderImage(sourcePath: string, outputPath: string): Promise<void> {
    return this.runFfmpeg(outputPath, (command) =>
      command
        .input(sourcePath)
        .outputOptions([
          '-vf',
          `scale=${THUMBNAIL_WIDTH}:-1`,
          '-vframes',
          '1',
        ])
        .format('mjpeg'),
    );
  }

  /**
   * Grabs a frame partway into an MJPEG source rather than frame 0, since
   * camera firmware can emit initialization frames (garbage/black) at the
   * very start of a recording. Falls back to frame 0 if the source is too
   * short to reach the skip target.
   */
  private async renderMjpegFrame(
    sourcePath: string,
    outputPath: string,
  ): Promise<void> {
    try {
      await this.renderMjpegFrameAt(
        sourcePath,
        outputPath,
        RECORDING_THUMBNAIL_FRAME_SKIP,
      );
    } catch {
      await rm(outputPath, { force: true });
      await this.renderMjpegFrameAt(sourcePath, outputPath, 0);
    }
  }

  private renderMjpegFrameAt(
    sourcePath: string,
    outputPath: string,
    skipFrames: number,
  ): Promise<void> {
    return this.runFfmpeg(outputPath, (command) =>
      command
        .input(sourcePath)
        .inputFormat('mpjpeg')
        .outputOptions([
          '-vf',
          `select='gte(n\\,${skipFrames})',scale=${THUMBNAIL_WIDTH}:-1`,
          '-vsync',
          '0',
          '-vframes',
          '1',
        ])
        .format('mjpeg'),
    );
  }

  private renderWaveform(sourcePath: string, outputPath: string): Promise<void> {
    return this.runFfmpeg(outputPath, (command) =>
      command
        .input(sourcePath)
        .videoCodec('png')
        .outputOptions([
          '-filter_complex',
          `showwavespic=s=${THUMBNAIL_WIDTH}x120:colors=white`,
          '-frames:v',
          '1',
          '-update',
          '1',
        ])
        .format('image2'),
    );
  }

  /**
   * ffmpeg exits 0 and fires 'end' even when a filter (e.g. a select= that
   * skips past the last available frame) matched nothing and wrote an empty
   * file, so success is verified by checking for non-zero output rather than
   * trusting the 'end' event alone.
   */
  private runFfmpeg(
    outputPath: string,
    configure: (command: ffmpeg.FfmpegCommand) => ffmpeg.FfmpegCommand,
  ): Promise<void> {
    return new Promise((resolvePromise, reject) => {
      configure(ffmpeg())
        .on('error', (error: Error) => reject(error))
        .on('end', () => {
          stat(outputPath)
            .then((info) =>
              info.size > 0
                ? resolvePromise()
                : reject(new Error('ffmpeg produced an empty output file')),
            )
            .catch(reject);
        })
        .save(outputPath);
    });
  }

  async exists(thumbnailPath: string): Promise<boolean> {
    try {
      await stat(thumbnailPath);
      return true;
    } catch {
      return false;
    }
  }
}
